In [1]:
import pandas as pd
from openpyxl.styles.builtins import percent

from extract.extract_s3 import extract_names_data, extract_qs_chat_phone_data
from config.config import AWS_BUCKET_NAME, AWS_RAW_EXPORT_FOLDER_PREFIX
from config.config import AWS_TODO_FILES_FOLDER
from extract.extract_s3 import extract_todo_tables

In [2]:
from config.config import AWS_TEAM_FOLDER_PREFIX

dfs = extract_qs_chat_phone_data(AWS_BUCKET_NAME, AWS_RAW_EXPORT_FOLDER_PREFIX)

chat_df = dfs['chat']
phone_df = dfs['phone']
qs_df = dfs['quality']
name_df = extract_names_data(AWS_BUCKET_NAME, AWS_TEAM_FOLDER_PREFIX)
todo_dfs = extract_todo_tables(AWS_BUCKET_NAME, AWS_TODO_FILES_FOLDER, sheet_name='CW1')

[{'Key': 'extracted-files-data/', 'LastModified': datetime.datetime(2026, 7, 3, 7, 21, 43, tzinfo=tzutc()), 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'ChecksumAlgorithm': ['CRC64NVME'], 'ChecksumType': 'FULL_OBJECT', 'Size': 0, 'StorageClass': 'STANDARD'}, {'Key': 'extracted-files-data/Statistic_user_20260629_075438.csv', 'LastModified': datetime.datetime(2026, 7, 3, 7, 50, 55, tzinfo=tzutc()), 'ETag': '"660356332374af2945f4de380e6d3fcb"', 'ChecksumAlgorithm': ['CRC64NVME'], 'ChecksumType': 'FULL_OBJECT', 'Size': 3225, 'StorageClass': 'STANDARD'}, {'Key': 'extracted-files-data/Vayu_History_Served_Requests_MOCK.csv', 'LastModified': datetime.datetime(2026, 7, 3, 7, 50, 55, tzinfo=tzutc()), 'ETag': '"a1e29afe0591b3db8bc958c1dc3c1f5f"', 'ChecksumAlgorithm': ['CRC64NVME'], 'ChecksumType': 'FULL_OBJECT', 'Size': 23165, 'StorageClass': 'STANDARD'}, {'Key': 'extracted-files-data/qs.xlsx', 'LastModified': datetime.datetime(2026, 7, 4, 18, 47, 15, tzinfo=tzutc()), 'ETag': '"ff5f76e15e07f6ac4591786d0ae04b87"', 'ChecksumAlgorithm': ['CRC64NVME'], 'ChecksumType': 'FULL_OBJECT', 'Size': 18214, 'StorageClass': 'STANDARD'}]
extracted-files-data/
extracted-files-data/Statistic_user_20260629_075438.csv

/Users/branimiranastasov/PycharmProjects/prod_report/.venv/lib/python3.13/site-packages/fsspec/registry.py:305: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

extracted-files-data/Vayu_History_Served_Requests_MOCK.csv
extracted-files-data/qs.xlsx
Skipping team-files/
Loaded names.xlsx:
       ID         Name         Phone         Chat          Email Address  \
0  521986    Agent One    One, Agent  Agnent Onne    agent.one@email.com
1  521987    Agent Two    Two, Agent    Agent Two    agent.two@email.com
2  521988  Agnet Three  Three, Agent  Agnet Three  agnet.three@email.com
3  521989   Agent Four   Four, Agent   Agent Four   agent.four@email.com
4  521990   Agent Five   Five, Agent   Agent Five   agent.five@email.com

               todo_file
0    agent_one_todo.xlsx
1    agent_two_todo.xlsx
2  agnet_three_todo.xlsx
3   agent_four_todo.xlsx
4   agent_five_todo.xlsx

In [3]:
chat_df.info()
chat_df_useful_cols = chat_df[['RecordId', 'EmployeeName']]
chat_df_useful_cols

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   RecordId                 104 non-null    str
 1   ParentRecordId           97 non-null     float64
 2   ChildRecordId            0 non-null      float64
 3   CustomerId               98 non-null     str
 4   RequestStatus            98 non-null     str
 5   ExitCode                 98 non-null     str
 6   EmployeeName             98 non-null     str
 7   UserId                   98 non-null     str
 8   GroupName                98 non-null     str
 9   PrimaryGroupName         98 non-null     str
 10  RequestTime              98 non-null     str
 11  WaitTime                 98 non-null     float64
 12  ServeTime                98 non-null     str
 13  EndTime                  98 non-null     str
 14  ServiceSeconds           98 non-null     float64
 15  Endby                    98 non-null     str
 16  ITSM Incident No         0 non-null      float64
 17  IsOutboundCall           98 non-null     float64
 18  useragent                98 non-null     str
 19  virtualagent             0 non-null      float64
 20  purgeddate               0 non-null      float64
 21  PreChatPurgedDate        0 non-null      float64
 22  AttemptCount             98 non-null     float64
 23  ContactTaskType          0 non-null      float64
 24  actualuseragent          98 non-null     str
 25  Transport                98 non-null     str
 26  WaitCount                98 non-null     float64
 27  ServiceCount             98 non-null     float64
 28  AgentLoadCount           98 non-null     float64
 29  ActiveAgentCount         98 non-null     float64
 30  ActiveAgentCountInGroup  98 non-null     float64
 31  calltype                 98 non-null     str
 32  teams.country            98 non-null     str
 33  teams.locale             98 non-null     str
dtypes: float64(16), str(18)
memory usage: 28.0 KB

                                              RecordId   EmployeeName
0                                                89613      Agent Six
1                                                89612      Agent Six
2                                                89611  Agent Fifteen
3                                                89610      Agent Six
4                                                89609    Agnet Three
..                                                 ...            ...
100  Report Generated By: Branimir Anastasov (EXTER...            NaN
101               From Date: 2026-06-22T00:00:00+00:00            NaN
102                 To Date: 2026-06-26T23:59:59+00:00            NaN
103                                         Group: All            NaN
104                                      TimeZone: UTC            NaN

[105 rows x 2 columns]

In [4]:
chat_df_useful_cols.isna().sum()

RecordId        1
EmployeeName    7
dtype: int64

In [5]:
chat_df_useful_cols.loc[chat_df_useful_cols['RecordId'].isna()]

   RecordId EmployeeName
98      NaN          NaN

In [6]:
chat_df_useful_cols.loc[chat_df_useful_cols['EmployeeName'].isna()]

                                              RecordId EmployeeName
98                                                 NaN          NaN
99      Report Generated At: 2026-06-29T05:57:49+00:00          NaN
100  Report Generated By: Branimir Anastasov (EXTER...          NaN
101               From Date: 2026-06-22T00:00:00+00:00          NaN
102                 To Date: 2026-06-26T23:59:59+00:00          NaN
103                                         Group: All          NaN
104                                      TimeZone: UTC          NaN

In [7]:
chat_df_no_na_values = chat_df_useful_cols.dropna()
chat_df_no_na_values.isna().sum()

RecordId        0
EmployeeName    0
dtype: int64

In [8]:
chat_df_no_na_values.info()

<class 'pandas.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RecordId      98 non-null     str
 1   EmployeeName  98 non-null     str
dtypes: str(2)
memory usage: 1.7 KB

In [9]:
def headers_to_snake_case(df):
    """Renames headers to snake_case"""
    df = df.copy()

    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", regex=True)
        .str.replace(r"([a-z0-9])([A-Z])", r"\1_\2", regex=True)
        .str.lower()
        .str.replace(r"[^a-z0-9]+", "_", regex=True)
        .str.strip("_")
    )

    return df

In [10]:
chat_headers_valid = headers_to_snake_case(chat_df_no_na_values)
chat_headers_valid

   record_id   employee_name
0      89613       Agent Six
1      89612       Agent Six
2      89611   Agent Fifteen
3      89610       Agent Six
4      89609     Agnet Three
..       ...             ...
93     89520   Agent Evelven
94     89519       Agent Two
95     89518  Agent Fourteen
96     89517   Agent Evelven
97     89516       Agent Two

[98 rows x 2 columns]

In [11]:
chat_headers_valid

   record_id   employee_name
0      89613       Agent Six
1      89612       Agent Six
2      89611   Agent Fifteen
3      89610       Agent Six
4      89609     Agnet Three
..       ...             ...
93     89520   Agent Evelven
94     89519       Agent Two
95     89518  Agent Fourteen
96     89517   Agent Evelven
97     89516       Agent Two

[98 rows x 2 columns]

In [12]:
phone_df

,User,Dialing attempts[Number],Accepted calls[Number],Connected to the caller[Number],Availability[%],Not answered total[Number],Busy[Number],Hang ups customer[Number],max. Ring Time reached[Number],other reasons[Number],...,Average call duration user[s],Ø-Connection setup user[s],Reaction time user total[s],Ø-Reaction time user[s],Ø-Sum Connection establishment + reaction time user[s],Wrap-up time[Min],Ø-Wrap-up time[s],Calls <=10s[Number],Forwarding[Number],",,,,,,"
0,"One, Agent",33,19,19,58,14,0,0,0,14,...,498.0,0.0,146,7.Jul,7.Jul,52.2,164.8,0,0,",,,,,"
1,"Two, Agent",33,25,25,76,8,0,0,5,3,...,131.0,0.1,259,10.Apr,10.May,182.2,437.3,0,0,",,,,,"
2,"Three, Agent",47,40,40,85,7,0,1,3,3,...,374.0,0.1,305,7.Jun,7.Jul,135.6,208.6,1,0,",,,,,"
3,"Four, Agent",1,1,1,100,0,0,0,0,0,...,180.0,0.0,15,15.0,15.0,2.0,120.0,0,0,",,,,,"
4,"Five, Agent",6,4,4,67,2,0,0,0,2,...,114.0,0.0,58,14.May,14.May,4.Mar,64.2,0,0,",,,,,"
5,"Six, Agent",6,6,6,100,0,0,0,0,0,...,425.0,0.2,89,14.Aug,15.0,7.Jul,77.0,0,0,",,,,,"
6,"Seven, Agent",1,1,1,100,0,0,0,0,0,...,586.0,0.0,6,6.0,6.0,8.0,480.0,0,0,",,,,,"
7,"Eight, Agent",5,4,4,80,1,0,0,0,1,...,781.0,0.0,34,8.May,8.May,29.Aug,446.2,0,0,",,,,,"
8,"Nine, Agent",9,9,9,100,0,0,0,0,0,...,544.0,0.3,89,9.Sep,10.Feb,20.Jul,138.0,0,0,",,,,,"
9,"Ten, Agent",6,6,6,100,0,0,0,0,0,...,830.0,0.0,69,11.May,11.May,11.Jul,139.8,1,0,",,,,,"
10,"Eleven, Agent",24,20,20,83,4,0,0,1,3,...,236.0,0.1,275,13.Aug,13.Aug,46.1,138.4,0,0,",,,,,"
11,"Twelve, Agent",16,7,7,44,9,0,0,2,7,...,423.0,0.0,113,16.Jan,16.Jan,30.Sep,265.3,0,0,",,,,,"
12,"Thirteen, Agent",22,17,17,77,5,0,0,5,0,...,229.0,0.1,202,11.Sep,11.Sep,62.1,219.1,0,0,",,,,,"
13,"Sixteen, Agent",11,7,7,64,4,0,1,2,1,...,284.0,0.3,96,13.Jul,14.0,14.0,120.0,0,0,",,,,,"
14,Summe,220,166,166,75,54,0,2,18,34,...,350.0,0.1,1756,10.Jun,10.Jul,607.3,222.2,2,0,",,,,,,"

In [13]:
cleaned_headers_phone = headers_to_snake_case(phone_df)
cleaned_headers_phone

,user,dialing_attempts_number,accepted_calls_number,connected_to_the_caller_number,availability,not_answered_total_number,busy_number,hang_ups_customer_number,max_ring_time_reached_number,other_reasons_number,...,average_call_duration_user_s,connection_setup_user_s,reaction_time_user_total_s,reaction_time_user_s,sum_connection_establishment_reaction_time_user_s,wrap_up_time_min,wrap_up_time_s,calls_10s_number,forwarding_number,
0,"One, Agent",33,19,19,58,14,0,0,0,14,...,498.0,0.0,146,7.Jul,7.Jul,52.2,164.8,0,0,",,,,,"
1,"Two, Agent",33,25,25,76,8,0,0,5,3,...,131.0,0.1,259,10.Apr,10.May,182.2,437.3,0,0,",,,,,"
2,"Three, Agent",47,40,40,85,7,0,1,3,3,...,374.0,0.1,305,7.Jun,7.Jul,135.6,208.6,1,0,",,,,,"
3,"Four, Agent",1,1,1,100,0,0,0,0,0,...,180.0,0.0,15,15.0,15.0,2.0,120.0,0,0,",,,,,"
4,"Five, Agent",6,4,4,67,2,0,0,0,2,...,114.0,0.0,58,14.May,14.May,4.Mar,64.2,0,0,",,,,,"
5,"Six, Agent",6,6,6,100,0,0,0,0,0,...,425.0,0.2,89,14.Aug,15.0,7.Jul,77.0,0,0,",,,,,"
6,"Seven, Agent",1,1,1,100,0,0,0,0,0,...,586.0,0.0,6,6.0,6.0,8.0,480.0,0,0,",,,,,"
7,"Eight, Agent",5,4,4,80,1,0,0,0,1,...,781.0,0.0,34,8.May,8.May,29.Aug,446.2,0,0,",,,,,"
8,"Nine, Agent",9,9,9,100,0,0,0,0,0,...,544.0,0.3,89,9.Sep,10.Feb,20.Jul,138.0,0,0,",,,,,"
9,"Ten, Agent",6,6,6,100,0,0,0,0,0,...,830.0,0.0,69,11.May,11.May,11.Jul,139.8,1,0,",,,,,"
10,"Eleven, Agent",24,20,20,83,4,0,0,1,3,...,236.0,0.1,275,13.Aug,13.Aug,46.1,138.4,0,0,",,,,,"
11,"Twelve, Agent",16,7,7,44,9,0,0,2,7,...,423.0,0.0,113,16.Jan,16.Jan,30.Sep,265.3,0,0,",,,,,"
12,"Thirteen, Agent",22,17,17,77,5,0,0,5,0,...,229.0,0.1,202,11.Sep,11.Sep,62.1,219.1,0,0,",,,,,"
13,"Sixteen, Agent",11,7,7,64,4,0,1,2,1,...,284.0,0.3,96,13.Jul,14.0,14.0,120.0,0,0,",,,,,"
14,Summe,220,166,166,75,54,0,2,18,34,...,350.0,0.1,1756,10.Jun,10.Jul,607.3,222.2,2,0,",,,,,,"

In [14]:
phone_df_useful = cleaned_headers_phone[['user', 'accepted_calls_number']]
phone_df_useful

               user  accepted_calls_number
0        One, Agent                     19
1        Two, Agent                     25
2      Three, Agent                     40
3       Four, Agent                      1
4       Five, Agent                      4
5        Six, Agent                      6
6      Seven, Agent                      1
7      Eight, Agent                      4
8       Nine, Agent                      9
9        Ten, Agent                      6
10    Eleven, Agent                     20
11    Twelve, Agent                      7
12  Thirteen, Agent                     17
13   Sixteen, Agent                      7
14            Summe                    166

In [15]:
phone_df_useful.isna().sum()

user                     0
accepted_calls_number    0
dtype: int64

In [16]:
qs_df = headers_to_snake_case(qs_df)
qs_df

,name,kw,datum,ticketnummer,tickettype,richtiger_kb,richtige_und_vollst_ndige_abarbeitung_kb,datenaufnahme_description,troubleshooting_performed_documented,solution_nachvollziehbar,...,focus_thema,ma_nahme,kommentar,betroffene_fg,ci,ersteller,verursacher_1,verursacher_2,verursacher_3,umgesetzte_ma_nahme
0,L2 Agent,KW1,2026-01-01,INC1465174,Request,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 1,CI 1,Agent One,NaN,NaN,NaN,NaN
1,L2 Agent,KW26,2026-01-01,INC1465175,Incident,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 2,CI 2,Agent Two,NaN,NaN,NaN,NaN
2,L2 Agent,KW26,2026-01-01,INC1465176,Incident,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 3,CI 3,Agnet Three,NaN,NaN,NaN,NaN
3,L2 Agent,KW26,2026-01-01,INC1465177,Incident,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 4,CI 4,Agent Four,NaN,NaN,NaN,NaN
4,L2 Agent,KW26,2026-01-01,INC1465178,Incident,Nein,Nein,Nein,Ja,Nein,...,Dokumentation,Sensibilisierung durch TL,"wrong ticket type, no KB",CI 5,CI 5,Agent Two,NaN,NaN,NaN,Mitarbeiter awarness
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,L2 Agent,KW26,2026-01-01,INC1465245,Incident,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 72,CI 72,Agent Seven,NaN,NaN,NaN,NaN
72,L2 Agent,KW26,2026-01-01,INC1465246,Incident,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 73,CI 73,Agent Six,NaN,NaN,NaN,NaN
73,L2 Agent,KW26,2026-01-01,INC1465247,Request,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 74,CI 74,Agnet Three,NaN,NaN,NaN,NaN
74,L2 Agent,KW26,2026-01-01,INC1465248,Request,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,CI 75,CI 75,Agent Six,NaN,NaN,NaN,NaN
75,NaN,NaN,NaT,NaN,NaN,Ja,Ja,Ja,Ja,Ja,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
qs_useful_cols = qs_df[['ticketnummer', 'ampelstatus_ticket_qs', 'ersteller']]

In [18]:
qs_useful_cols

   ticketnummer ampelstatus_ticket_qs    ersteller
0    INC1465174            in Ordnung    Agent One
1    INC1465175            in Ordnung    Agent Two
2    INC1465176            in Ordnung  Agnet Three
3    INC1465177            in Ordnung   Agent Four
4    INC1465178         Durchgefallen    Agent Two
..          ...                   ...          ...
71   INC1465245            in Ordnung  Agent Seven
72   INC1465246            in Ordnung    Agent Six
73   INC1465247            in Ordnung  Agnet Three
74   INC1465248            in Ordnung    Agent Six
75          NaN            in Ordnung          NaN

[76 rows x 3 columns]

In [19]:
qs_useful_cols.isna().sum()

ticketnummer             1
ampelstatus_ticket_qs    0
ersteller                1
dtype: int64

In [20]:
qs_useful_cols['ticketnummer'].duplicated().sum()

np.int64(0)

In [21]:
name_df

,ID,Name,Phone,Chat,Email Address,todo_file
0,521986,Agent One,"One, Agent",Agnent Onne,agent.one@email.com,agent_one_todo.xlsx
1,521987,Agent Two,"Two, Agent",Agent Two,agent.two@email.com,agent_two_todo.xlsx
2,521988,Agnet Three,"Three, Agent",Agnet Three,agnet.three@email.com,agnet_three_todo.xlsx
3,521989,Agent Four,"Four, Agent",Agent Four,agent.four@email.com,agent_four_todo.xlsx
4,521990,Agent Five,"Five, Agent",Agent Five,agent.five@email.com,agent_five_todo.xlsx
5,521991,Agent Six,"Six, Agent",Agent Six,agent.six@email.com,agent_six_todo.xlsx
6,521992,Agent Seven,"Seven, Agent",Agent Seven,agent.seven@email.com,agent_seven_todo.xlsx
7,521993,Agent Eight,"Eight, Agent",Agent Eight,agent.eight@email.com,agent_eight_todo.xlsx
8,521994,Agent Nine,"Nine, Agent",Agent Nine,agent.nine@email.com,agent_nine_todo.xlsx
9,521995,Agent Ten,"Ten, Agent",Agent Ten,agent.ten@email.com,agent_ten_todo.xlsx
10,521996,Agent Eleven,"Eleven, Agent",Agent Evelven,agent.eleven@email.com,agent_eleven_todo.xlsx
11,521997,Agent Twelve,"Twelve, Agent",Agent Twelve,agent.twelve@email.com,agent_twelve_todo.xlsx
12,521998,Agent Thirteen,"Thirteen, Agent",Agent Thirteen,agent.thirteen@email.com,agent_thirteen_todo.xlsx
13,521999,Agent Fourteen,"Fourteen, Agent",Agent Fourteen,agent.fourteen@email.com,agent_fourteen_todo.xlsx
14,522000,Agent Fifteen,"Fifteen, Agent",Agent Fifteen,agent.fifteen@email.com,agent_fifteen_todo.xlsx
15,522001,Agent Sixteen,"Sixteen, Agent",Agen Sixteen,agent.sixteen@email.com,agent_sixteen_todo.xlsx
16,522002,Agent Seventeen,"Seventeen, Agent",Agent Seventeen,agent.seventeen@email.com,agent_seventeen_todo.xlsx

In [22]:
print(name_df.set_index('Chat')["Name"])

Chat
Agnent Onne              Agent One
Agent Two                Agent Two
Agnet Three            Agnet Three
Agent Four              Agent Four
Agent Five              Agent Five
Agent Six                Agent Six
Agent Seven            Agent Seven
Agent Eight            Agent Eight
Agent Nine              Agent Nine
Agent Ten                Agent Ten
Agent Evelven         Agent Eleven
Agent Twelve          Agent Twelve
Agent Thirteen      Agent Thirteen
Agent Fourteen      Agent Fourteen
Agent Fifteen        Agent Fifteen
Agen Sixteen         Agent Sixteen
Agent Seventeen    Agent Seventeen
Name: Name, dtype: str

In [23]:
for key, df in todo_dfs.items():
    print(df)

      Emails      ToDo
0   INC12345  INC23456
1   INC12346  INC23457
2   INC12347  INC23458
3   INC12348  INC23459
4   INC12349  INC23460
5   INC12350  INC23461
6   INC12351  INC23462
7   INC12352  INC23463
8   INC12353  INC23464
9   INC12354  INC23465
10  INC12355  INC23466
11  INC12356  INC23467
12  INC12357  INC23468
13  INC12358  INC23469
14  INC12359  INC23470
15  INC12360  INC23471
16  INC12361  INC23472
17  INC12362       NaN
18  INC12363       NaN
19  INC12364       NaN
20  INC12365       NaN
21  INC12366       NaN
22  INC12367       NaN
23  INC12368       NaN
24  INC12369       NaN
25  INC12370       NaN
26  INC12371       NaN
27  INC12372       NaN
28  INC12373       NaN
29  INC12374       NaN
30  INC12375       NaN
31  INC12376       NaN
32  INC12377       NaN
33  INC12378       NaN
34  INC12379       NaN
35  INC12380       NaN
36  INC12381       NaN
37  INC12382       NaN
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
       Emails       ToDo
0    INC56789  INC122345
1    INC56790  INC122346
2    INC56791  INC122347
3    INC56792  INC122348
4    INC56793  INC122349
..        ...        ...
154       NaN  INC122499
155       NaN  INC122500
156       NaN  INC122501
157       NaN  INC122502
158       NaN  INC122503

[159 rows x 2 columns]
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
      Emails      ToDo
0   INC12345  INC56789
1   INC12346  INC56790
2   INC12347  INC56791
3   INC12348  INC56792
4   INC12349  INC56793
5   INC12350  INC56794
6   INC12351       NaN
7   INC12352       NaN
8   INC12353       NaN
9   INC12354       NaN
10  INC12355       NaN
11  INC12356       NaN
12  INC12357       NaN
13  INC12358       NaN
14  INC12359       NaN
15  INC12360       NaN
16  INC12361       NaN
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []
Empty DataFrame
Columns: [Emails, ToDo]
Index: []

In [24]:
chat_df_useful_cols.columns

Index(['RecordId', 'EmployeeName'], dtype='str')

In [25]:
chats_count = (chat_df_useful_cols.groupby('EmployeeName')
               .agg(chats_count=('RecordId', 'count'))
               .reset_index()).sort_values(by='EmployeeName')
chats_count

     EmployeeName  chats_count
0   Agent Evelven           12
1   Agent Fifteen            9
2      Agent Four           13
3  Agent Fourteen            7
4      Agent Nine            5
5       Agent Six           18
6       Agent Ten           11
7  Agent Thirteen            1
8       Agent Two           13
9     Agnet Three            9

In [26]:
qs_useful_cols

   ticketnummer ampelstatus_ticket_qs    ersteller
0    INC1465174            in Ordnung    Agent One
1    INC1465175            in Ordnung    Agent Two
2    INC1465176            in Ordnung  Agnet Three
3    INC1465177            in Ordnung   Agent Four
4    INC1465178         Durchgefallen    Agent Two
..          ...                   ...          ...
71   INC1465245            in Ordnung  Agent Seven
72   INC1465246            in Ordnung    Agent Six
73   INC1465247            in Ordnung  Agnet Three
74   INC1465248            in Ordnung    Agent Six
75          NaN            in Ordnung          NaN

[76 rows x 3 columns]

In [30]:
qs_score = qs_useful_cols.assign(
    is_in_ordnung=lambda x:
    x['ampelstatus_ticket_qs'].eq('in Ordnung')).groupby('ersteller').agg(
    total_tickets=('ticketnummer', 'count'),
    tickets_in_ordnung=('is_in_ordnung', 'sum')
).assign(qs_percent=lambda x: x['tickets_in_ordnung'] / x['total_tickets'] * 100).round(2).reset_index().sort_values(by='ersteller')
qs_score

         ersteller  total_tickets  tickets_in_ordnung  qs_percent
0      Agent Eight              5                   5      100.00
1     Agent Eleven              5                   4       80.00
2    Agent Fifteen              3                   3      100.00
3       Agent Five              5                   5      100.00
4       Agent Four              5                   5      100.00
5   Agent Fourteen              5                   5      100.00
6       Agent Nine              5                   5      100.00
7        Agent One              5                   2       40.00
8      Agent Seven              5                   5      100.00
9        Agent Six              6                   6      100.00
10       Agent Ten              5                   4       80.00
11  Agent Thirteen              5                   5      100.00
12    Agent Twelve              5                   5      100.00
13       Agent Two              5                   4       80.00
14     Agnet Three              6                   4       66.67

In [31]:
name_df

,ID,Name,Phone,Chat,Email Address,todo_file
0,521986,Agent One,"One, Agent",Agnent Onne,agent.one@email.com,agent_one_todo.xlsx
1,521987,Agent Two,"Two, Agent",Agent Two,agent.two@email.com,agent_two_todo.xlsx
2,521988,Agnet Three,"Three, Agent",Agnet Three,agnet.three@email.com,agnet_three_todo.xlsx
3,521989,Agent Four,"Four, Agent",Agent Four,agent.four@email.com,agent_four_todo.xlsx
4,521990,Agent Five,"Five, Agent",Agent Five,agent.five@email.com,agent_five_todo.xlsx
5,521991,Agent Six,"Six, Agent",Agent Six,agent.six@email.com,agent_six_todo.xlsx
6,521992,Agent Seven,"Seven, Agent",Agent Seven,agent.seven@email.com,agent_seven_todo.xlsx
7,521993,Agent Eight,"Eight, Agent",Agent Eight,agent.eight@email.com,agent_eight_todo.xlsx
8,521994,Agent Nine,"Nine, Agent",Agent Nine,agent.nine@email.com,agent_nine_todo.xlsx
9,521995,Agent Ten,"Ten, Agent",Agent Ten,agent.ten@email.com,agent_ten_todo.xlsx
10,521996,Agent Eleven,"Eleven, Agent",Agent Evelven,agent.eleven@email.com,agent_eleven_todo.xlsx
11,521997,Agent Twelve,"Twelve, Agent",Agent Twelve,agent.twelve@email.com,agent_twelve_todo.xlsx
12,521998,Agent Thirteen,"Thirteen, Agent",Agent Thirteen,agent.thirteen@email.com,agent_thirteen_todo.xlsx
13,521999,Agent Fourteen,"Fourteen, Agent",Agent Fourteen,agent.fourteen@email.com,agent_fourteen_todo.xlsx
14,522000,Agent Fifteen,"Fifteen, Agent",Agent Fifteen,agent.fifteen@email.com,agent_fifteen_todo.xlsx
15,522001,Agent Sixteen,"Sixteen, Agent",Agen Sixteen,agent.sixteen@email.com,agent_sixteen_todo.xlsx
16,522002,Agent Seventeen,"Seventeen, Agent",Agent Seventeen,agent.seventeen@email.com,agent_seventeen_todo.xlsx

In [41]:
names_mapper = name_df.set_index('todo_file')["Name"]
rows = []

for file_name, df in todo_dfs.items():
   counts = df[['Emails', 'ToDo']].count()
   rows.append({
        'user': names_mapper.get(file_name),
        'emails_count': counts['Emails'],
       'todo_counts': counts['ToDo']
   }
   )

todo_summary = pd.DataFrame(rows).sort_values(by='user')

todo_summary

               user  emails_count  todo_counts
0       Agent Eight            38           17
1      Agent Eleven             0            0
2     Agent Fifteen             0            0
3        Agent Five             0            0
4        Agent Four            82          159
5    Agent Fourteen             0            0
6        Agent Nine             0            0
7         Agent One            17            6
8       Agent Seven             0            0
9   Agent Seventeen             0            0
10        Agent Six             0            0
11    Agent Sixteen             0            0
12        Agent Ten             0            0
13   Agent Thirteen             0            0
14     Agent Twelve             0            0
15        Agent Two             0            0
16      Agnet Three             0            0